### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Kaz",
  "email": "em@il.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "em@il.com",
  "password": "password"
}

###
http://localhost:3000/users/1.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDgwNzYzNzF9.Fzt3FCx7pOp4QzKrJTwHx68k6ERUNLs6feb3LexlAxo

Content-Type: application/json
